[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qelm"      
version = "0.0.1.dev0"
description = "Quantum-Enhanced Language Model (full repo snapshot)"
authors = [{name="Brenton Carter"}]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.9"

# core runtime deps
dependencies = [
  "qiskit-aer>=0.12",
  "qiskit>=1.0",
  "tensorflow>=2.16",
  "nltk>=3.8",
  "psutil>=5.9",
  "matplotlib>=3.8",
  "tk",                    # GUI
]

[project.scripts]
qelm-gui   = "qelm.gui.launcher:main"   
qelm-train = "qelm.cli.train:main"
