# .github/workflows/release.yml
name: release-qelm
on:
  push:
    tags: ["v*"]        

jobs:
  build-and-publish:
    permissions:
      id-token: write    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.x"}
      - run: |
          python -m pip install build
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1
