# .github/workflows/release.yml
name: release-qelm
on:
  push:
    tags: ["v*"]              # e.g. v1.3.0

jobs:
  build-and-publish:
    permissions:
      id-token: write         # OIDC token for PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.x"}
      - run: |
          python -m pip install build
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1
